name: Aprendiendo Contextos
run-name: Ejecucion de algunos jobs según contexto
on:
  push:
    branches: [master]
  # pull_request: []
env:
  nombre: Diego
  apellido: Forero
jobs:
  leer-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Echo variables ENV
        run: echo "Hola persona llamada ${{env.nombre}} - ${{env.apellido}}"
      - name: Echo variables GITHUB
        run: echo "NombreUsuario = ${{ github.actor }} en el la rama = ${{github.ref}} del repositorio ${{github.repository}}"
      - name: Echo <context> completo
        run: echo ${{ github }}
