name: Aprendiendo Secretos
run-name: Aprendiendo Secretos (run-name)
on: workflow_dispatch
env:
  DIA_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Holandaaaaa
    steps:
      - name: Saludo variables
        run: echo "$SALUDO, ${{vars.NOMBRE}}, Hoy es ${{env.DIA_SEMANA}}"
  saludo-secretos:
    runs-on: ubuntu-latest
    env:
      SALUDO: Holandaaaaa
    steps:
      - name: Saludo secretos
        run: echo "$SALUDO, ${{vars.NOMBRE}}, Tu clave es ${{secrets.DB_PASSWORD}}"
